context:
  version: "0.1.9"

package:
  name: tirith
  version: ${{ version }}

source:
  url: https://github.com/sheeki03/tirith/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 0b1d2e5095e5e97e92a2a51162fce38294f1b7f494fb799a58d92e57df0d8515

build:
  number: 0
  script:
    env:
      CARGO_PROFILE_RELEASE_STRIP: symbols
      CARGO_PROFILE_RELEASE_LTO: fat
    content:
      - if: unix
        then:
          - cargo auditable install --locked --no-track --bins -j ${CPU_COUNT} --root ${{ PREFIX }} --path crates/tirith
        else:
          - cargo auditable install --locked --no-track --bins -j %CPU_COUNT% --root %LIBRARY_PREFIX% --path crates/tirith
      - cargo-bundle-licenses --format yaml --output ./THIRDPARTY.yml

requirements:
  build:
    - ${{ stdlib('c') }}
    - ${{ compiler('c') }}
    - ${{ compiler('rust') }}
    - cargo-bundle-licenses
    - cargo-auditable

tests:
  - script: tirith --help

about:
  homepage: https://github.com/sheeki03/tirith
  summary: Your browser would catch this. Your terminal won'.
  description: |
    Tirith guards the gate — intercepts suspicious URLs, ANSI injection, and pipe-to-shell attacks before they execute.
  license: AGPL-3.0-only
  license_file:
    - LICENSE-AGPL
    - LICENSE-COMMERCIAL
    - THIRDPARTY.yml

extra:
  recipe-maintainers:
    - claudiushaag
